name: Custom Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      # Step 4: Install Black (Linter)
      - name: Install Black
        run: python3 -m pip install black

      # Step 5: Run Black Linter (Dry Run)
      - name: Run Black Linter
        id: black-lint
        run: |
          black --check .
        continue-on-error: true

      # Step 6: Check Linter Exit Code and Print Custom Messages
      - name: Check Linter Status
        run: |
          if [ ${{ steps.black-lint.outcome }} == "failure" ]; then
            echo "Some linting errors were found."
            exit 1
          else
            echo "Yay! Linting went perfectly."
          fi
